### ISSUE TITLE
Footnotes not displaying

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#100]
Footnotes not displaying correctly. Ex. http://hcmc.uvic.ca/confederation/en/lgNFNC_1947-04-10.html string "Report of the Mining Committee:[1] Committee of the Whole"

**Comment by martindholmes** [comment]
Looks like only half of the functionality is implemented. I think it's my problem, so I'm taking the ticket for the moment.

**Comment by martindholmes** [comment]
Fixed in commit 1faf2caed.
