### ISSUE TITLE
Website linking French and English Numbered Treaties

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#101]
The French and English language buttons in the header do not appear to be linking English and French editions of the numbered Treaties correctly. Try, for example, http://hcmc.uvic.ca/confederation/en/treaty_7.html. When I click the "FR" button, my browser goes to http://hcmc.uvic.ca/confederation/fr/treaty_7.html instead of http://hcmc.uvic.ca/confederation/en/treaty_7_fr.html (the path is wrong, but the page functions).

**Comment by martindholmes** [comment]
Probably because the treaties were introduced after the plan for linking between French and English documents was created. Every time we add more different types of content, stuff will break.

**Comment by martindholmes** [comment]
Fix for this: the code in html_split_languages.xsl which looks for a French equivalent file looks for _fr_, but here _fr is at the end of the id. Change French filenames and ids to treaty_fr_2 etc. That should fix it I think.

**Comment by martindholmes** [comment]
That didn't fix the problem by itself. More to do here.

**Comment by martindholmes** [comment]
Fixed in commit 43fab9501. Closing.
