### ISSUE TITLE
Team page images

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#103]
Many team page images are not displaying correctly. It does not appear to be a broken link issue.

**Comment by martindholmes** [comment]
I think they're mostly caused by a hopeless mess in the filenaming department -- upper case and lower case all mixed up, accented characters, and all sorts of inconsistencies. Most of the missing images seem to have bad links. Someone who can be precise and meticulous needs to sort the filenames out, then fix the links. I've just tidied up a similar mess in the portraits folder.

**Comment by martindholmes** [comment]
Actually, these photos are a real disaster. There are multiple copies of the same image -- Hamilton-Rob.png and Hamilton-Rob-1.png, Krucker-Madeleine.jpg and Krucker-Madeleine-1.jpg, and so on. Could you get rid of all the dupes?

**Comment by DanielHeidt** [comment]
Resolved, push `67bfab1`

**Comment by DanielHeidt** [comment]
I’m sorry to bother you with this again… almost none of the images in the team page are working. I checked team.html and Oxygen doesn’t report any code errors. I spot checked a bunch of file names and they look fine to me and yet nearly all of the image links are broken. When I open the page locally, all of the links work—though I know that is not the best test. Is there any chance I’m doing something wrong with the directory in the code? Alternatively, is there something with the build process?

**Comment by martindholmes** [comment]
Ad far as I can see, filenames in the team.html page don't match filenames in the images/team folder.

**Comment by DanielHeidt** [comment]
Strange. I updated the file names to match before the break (push #103). All characters are now lower case. Are my changes showing up on your end?

**Comment by DanielHeidt** [comment]
Verified that push didn't update all changes. Problem fixed commit `eb8e1a1`

**Comment by martindholmes** [comment]
I can't rebuild until I get to work on January 2, I'm afraid. My work computer is powered down.
