### ISSUE TITLE
Profile image credits

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#105]
Hi Martin,

I noticed that the profile popups do not have photo credits as per copyright requirements and believe I have done the work to make this relatively simple to implement. I spent considerable portion of today converting the original spreadsheet the volunteers used to track this into decent XML providing the IDs and links. Github isn't letting me attach an xml file to this ticket so I have emailed it to you separately. 

I assume it would be simplest to integrate this information into personography.xml and then pull from it when rebuilding the site, but I leave that to you. 

I think the best place to put the credit text would be directly below the image in the popup. You can see what I mean here: http://biographi.ca/en/bio/tupper_charles_14E.html.

Below are some examples of how this info could listed in the popup:
- ANNA1 would = 
`<a lang="en" href="https://novascotia.ca/archives/notman/archives.asp?ID=436">Image Source</a>`
`<a lang="fr" href="https://novascotia.ca/archives/notman/archives.asp?ID=436">Provenance</a>`

Note the links are the same in this example because there is no French-language edition of the page.

- ADAM1 would = 
`<a lang="en" href="http://collectionscanada.gc.ca/ourl/res.php?url_ver=Z39.88-2004&url_tim=2017-02-25T15%3A09%3A01Z&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&rft_dat=3212599&rfr_id=info%3Asid%2Fcollectionscanada.gc.ca%3Apam&lang=eng">Image Source</a>`
`<a lang="fr" href="http://collectionscanada.gc.ca/ourl/res.php?url_ver=Z39.88-2004&url_tim=2017-02-25T15%3A09%3A01Z&url_ctx_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Actx&rft_dat=3212599&rfr_id=info%3Asid%2Fcollectionscanada.gc.ca%3Apam&lang=fre">Provenance</a>`

Note the links here are different in this example because a French-language edition of the page exists.

**Comment by martindholmes** [comment]
This might be an issue for Frank, since he's the one who set the images up as background-images rather than regular images; I've never understood why. If I can reverse that decision and make them regular images, it'll be easier to do.

**Comment by DanielHeidt** [comment]
As per our meeting today, please find attached an updated XML file. I also included the original CSV in case that is more useful.

[Confederation Debates Image Tracking.zip](https://github.com/TheCanadianConfederationDebates/TCCD/files/1616202/Confederation.Debates.Image.Tracking.zip)

**Comment by martindholmes** [comment]
I've been trying to access these URLs at the LAC, and they all fail; it looks like these are all session-based URLs that would only work for the browser session in which the search was made. It looks like the URLs will have to be ignored, and the id number used in an alternative URL like this (where the id is 3475472:

http://collectionscanada.gc.ca/pam_archives/index.php?fuseaction=genitem.displayItem&rec_nbr=3475472&lang=eng

**Comment by martindholmes** [comment]
Image provenance data has now been integrated into the personography. @DanielHeidt @lyallg please note: if you add a portrait image to the portraits folder, you must now create a `<figure>` element for it inside the person entry in the personography, following the examples of the existing figures. Simply adding the jpg file to the folder will no longer be sufficient to make it show up on the site.

I now have to rewrite the processing of people into popups so that the images are provided along with their source. This means abandoning Frank's approach of using the image as a background graphic, and instead making it an actual figure in the HTML. That may take a little while.

**Comment by martindholmes** [comment]
This is now completed.
