### ISSUE TITLE
Witnesses to Parliamentary bodies

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#109]
I've run into an encoding question that perhaps @lyallg can answer so that @martindholmes can focus on other stuff? 

RICH4 was a witness to the "MB Government" — as such he has no riding but answered questions near present-day Winnipeg. Should I create a custom riding for this purpose, or is there a better way to encode this `<placename>` into personography.xml?

**Comment by lyallg** [comment]
@DanielHeidt I think a custom placename makes sense. It would be similar to the treaty placenames. I imagine you are attempting to avoid having him lumped into a Winnipeg riding, which he never represented? Did his actions take place at Fort Garry or one of the local communities, St Boniface (this may be a riding too) etc.?

**Comment by DanielHeidt** [comment]
It was Upper Fort Gary. Thanks for the advice. I added a node to placeography.xml and inputted the ID into the appropriate place into personography.xml.

**Comment by martindholmes** [comment]
This makes no sense to me. He didn't represent this place in any way, so why would he be on the map? I think the idea that the map is the interface to everything is just misguided. It's one of many interfaces; most people will want to see proper contents pages (which we have, but which don't get properly linked from anywhere).

**Comment by lyallg** [comment]
I'm not sure there is an easy solution, but if there are placenames associated with locations that treaties were signed at, then this is a comparable situation being that he acted as a witness at Fort Garry. It would be cleaner to take out every place that does not indicate a riding that a person represented I suppose but at the cost of a more inclusive history. Perhaps this is explained in the introductory sections? That is that locations on the map indicate either ridings people represented or places where people interacted in negotiations over confederation?

**Comment by lyallg** [comment]
A proper contents page preceding the map I think would be useful.

**Comment by DanielHeidt** [comment]
I have added the following note to FAQ.html.

> The nodes on the project's landing page map are the approximate centre points of federal and provincial ridings, meeting or signing locations for treaties between Indigenous Peoples and the Crown, or the location of legislatures where witnesses testified. Each node was plotted by a team of four volunteers from across the country who consulted dozens of historical maps and written descriptions.
