### ISSUE TITLE
DCB logo

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#116]
Please change the Dictionary of Canadian Biography (DCB) logo to the new provided image on the following types of pages:
1) Footers on all pages (ex. the index, purpose and team pages).
2) popups on the landing page map (http://hcmc.uvic.ca/confederation/en/index.html)
3) Historical figure pages (ex. http://hcmc.uvic.ca/confederation/en/LANG1.html)
4) popups on debate days (http://hcmc.uvic.ca/confederation/en/lgHC_NFLD_1888-04-09.html)

For 2, 3, and 4, please also re-position the DCB logo to appear below the image credit.

**Comment by martindholmes** [comment]
After discussion, the solution to the popup/AJAX issue (2 & 4) is:

1. Provide the person's name in red, as a link;
2. Process any DCB link into a block-level logo image (new logo) below it;
3. Start the next line with "_This historical figure_ participated in...".

**Comment by martindholmes** [comment]
I've done 2,3,4. Handing over to Frank to do the footer. The new logo is in code/html/images/logos.

**Comment by DanielHeidt** [comment]
Number 1 also complete.

**Comment by martindholmes** [comment]
I'll rebuild when I get back to the office on Tuesday.

**Comment by DanielHeidt** [comment]
No hurry. Thanks!

**Comment by martindholmes** [comment]
Rebuilt. Closing this one.
