### ISSUE TITLE
footers

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#120]
Please standardize the image footer sizes.

Please also add the following images and links (I can do this step once the images are standardized, if desired):
UBC Press - link to https://www.ubcpress.ca/new-histories-for-old
UCP Press - link to https://press.ucalgary.ca/

**Comment by DanielHeidt** [comment]
images and links are in place. Resizing still has to be done.

**Comment by martindholmes** [comment]
I think this is done, although there's a weird effect when you reduce the window-width to mobile-size: the images in the footer seem to get larger.

**Comment by martindholmes** [comment]
Closing, since it seems to be fixed.
