### ISSUE TITLE
minor page number bug

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#126]
On https://hcmc.uvic.ca/confederation/en/lgNFNC_1948-01-30.htmlm some of the page numbers (displayed on the left margin in red boxes) are not centered. Ex. 1456 has this problem. Some of the other numbers for the page are fine.

I looked at lgNFNC_1948-01-30.xml and I don't see additional spaces that might have produced this issue. Any idea what the problem might be?

**Comment by martindholmes** [comment]
It was caused by an indent on the containing paragraph, which was inherited by the page number. Just had to set text-indent to zero specifically on the class for the forme works.
