### ISSUE TITLE
Historical figure profiles debate day order

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#128]
A minor fix: the debate days on the historical figure pages appear to be correctly year to year and month to month. But the day to day appears to not be fully ordered. Please consider 

https://hcmc.uvic.ca/confederation/en/TACH1.html

as an example. Could all years, months and dates, start with earliest (i.e. January 1) and please go to latest (i.e. Dec 31)?

**Comment by martindholmes** [comment]
Fixed in commit 5bd242402.
