### ISSUE TITLE
minor language issue with header on H of C TOC pages

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#129]
It's a minor thing, but there appears to be a minor issue with the headers for the TOC for each H of C page. Ex. https://hcmc.uvic.ca/confederation/en/lgHC_BC.html and https://hcmc.uvic.ca/confederation/en/lgHC_NFLD.html. I think this is coming from taxonomy - are the <gloss> fields getting selected correctly during the page build?

**Comment by martindholmes** [comment]
I think your diagnosis is right. I'll fix it when I get back to the office next week.

**Comment by martindholmes** [comment]
This should be fixed in commit https://github.com/TheCanadianConfederationDebates/TCCD/commit/d4e8501fffd7d98514a65b12757deaf69ca33ab9
