### ISSUE TITLE
Populating map content

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#130]
I was looking at the map at the top of the landing page, and I'm wondering if some of the data in the popups is being correctly populated? **To be clear the "People" section looks great, and does not require any change.** The "Debates and documents" section, however, appears to be accidentally overpopulated because it is incorporating content from other ridings from historical figures who represented multiple places during other stages of their political careers.

Since the map nodes indicate places rather than people, it would be more intuitive if it only listed debate days / treaty negotiations where the representative from that riding / signing location is encoded as a participant.

Take, for example, ARCT1 (displayed near the top of the Yukon Territory). The "Debates and Documents" section of the popup for this node includes Treaties 8 and 11. Treaty 8 is much farther south and should therefore not appear as in the "Treaty Texts" section for ARCT1. I think the reason this is occurring is because CONR3 was a witness at Treaty 8 but also worked as a Commissioner for Treaty 11. While it is true that CONR3 contributed to Treaty 8, this document was not signed at ARCT1. Thus, while Treaty 11 should (and does) appear in the summary for CONR3 in the "People" section of the popup for ARCT1, it should not appear in the "Debates and Documents" section of ARCT1 because no one signed Treaty 8 at this location.

Similarly, CONR3 should appear in the "People Section" for PEAC2 - a site where hCONR3 actually witnessed the signing of Treaty 8. But Treaties 4, 6, 7 and 11 should not appear in the "Treaty Texts" section of PEAC2.

The same logic appears to be driving the "Debates and documents" sections of the popup for legislative ridings. HAMI4, for example, was a provincial / territorial riding - yet the "Debates and Documents" section of its popup contains content from the House of Commons. I believe this additional content is being shown in this section because MAGI1 participated in these additional debates from another riding during a later part of his political career.

**I bring this up now so that we can think a bit about what is knowable and whether there is logic to better constrain the "Debates and Documents" section.** Depending on what is knowable from the current data, it might be possible to add an extra parameter that constrains this list without creating a bunch of extra work. If all else fails, we could consider deleting the separate "Debates and documents" section, and keep the "People" with their individual "Debates and documents" drop-downs - which I gather are much simpler to populate and appear to be working fine.

P.S. if this sounds familiar, we discussed it in a file entitled "website design popup template.docx". I believe Martin took some additional notes during a subsequent meeting, which I have not been able to find so far, but I am glad to provide the original file if that helps.

**Comment by martindholmes** [comment]
You can see how this is being done:

https://github.com/TheCanadianConfederationDebates/TCCD/blob/master/code/xslt/tei_to_ajax_fragments_master.xsl#L165

Basically: get all the people associated with this place;
For each of those people, get all the documents associated with them.

That inevitably retrieves documents not connected with the place, but since there is no direct connection between documents and places other than through people, there's no other way to do this. The only alternatives are either:

1. Create a list of linked documents for every place entry; or
2. Suppress the list of documents completely, on the basis that it's misleading.

#1 is a lot of work for somebody. #2 will simplify the interface considerably by removing documents from the info about a place, but arguably makes it less useful.

**Comment by martindholmes** [comment]
Solution agreed 2018-11-19: eliminate the section "Debates and Documents" in the place record. This forces people to discover documents through the people they are associated with, which makes it easier to see that they may or may not be relevant to that specific place.

**Comment by martindholmes** [comment]
Done in commit #68c09ac41.
