### ISSUE TITLE
Legacy website design

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#20]
List of possible features for legacy website to discuss at future date:
- simple landing page with brief about, map browsing interface, browse by volume interface (Frank is already working on this for existing site) and links to team members
- host quotes of the day in searchable as well as png form (the latter will facilitate sharing)
- share buttons for social media
- search function by name (ID #), keyword, string
- Clicking speaker names could open new page with search for other comments by that individual
- page to download datasets (as separate volumes?)

**Comment by martindholmes** [comment]
All done except for search, which is in #89.
