### ISSUE TITLE
Taxonomy of legislatures required

### ISSUE THREAD

**Issue by martindholmes** [TheCanadianConfederationDebates/TCCD#22]
We need to specify a formal list of the legislative bodies whose proceedings fall into our dataset, and assign unique identifiers to them. Dan, could you get us started with a prose list, and then we'll turn it into a taxonomy?

**Comment by DanielHeidt** [comment]
The House of Commons

- Legislative Council of British Columbia
- Legislative Assembly of the North-West Territories
- The Convention  of 40 / La Grande Convention
- Legislative Assembly of Assiniboia / l’Assemblée législative d’Assiniboia
- Provincial Parliament of Canada (the single publication includes the Legislative Assembly and Legislative Council's respective debates) / Parlement Provincial du Canada
- Legislative Assembly of New Brunswick
- Legislative Assembly of Nova Scotia
- Legislative Assembly of Prince Edward Island
- Legislative Assembly of Newfoundland

Let me know when you need a similar list for the Indigenous sources. The RA is in the process of finalizing a list of Indigenous sources / records of negotiation, so I could only provide you with a partial list at the moment.

**Comment by martindholmes** [comment]
@DanielHeidt This looks good, but I'm not sure what the "Provincial Parliament of Canada" is -- the way it's defined makes it look like a publication rather than an actual assembly. Could you forgive my ignorance and clarify that?

**Comment by DanielHeidt** [comment]
@martindholmes your observation is actually very astute. The Province of Canada (Ontario and Quebec were one colony in the decades immediately preceding Confederation) each sent representatives to a Legislative Assembly and a Legislative Council. Unlike all of the other provinces, however, the colony's only verbatim record is a single book containing the discussions in both houses.

So the question is as follows: do we encode each legislature's content separately (they are already clearly demarcated with headings), or do we encode the book as a single volume? I do not currently have a clear preference either way, and would appreciate your input on which would be a more sensible approach.

**Comment by martindholmes** [comment]
@DanielHeidt I think we should identify each legislature separately; the source description in the TEI file will have full details of the source volume itself. So if I understand correctly, we actually have:

Province of Canada Legislative Assembly
Province of Canada Legislative Council

and their deliberations happen to be recorded in the same publication.

**Comment by DanielHeidt** [comment]
@martindholmes sounds good to me

**Comment by martindholmes** [comment]
@DanielHeidt Will there be nothing from the Senate?
