### ISSUE TITLE
Page selection explanations PEI

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#23]
Hi Dan,

We need a couple explanations on page selection for TEI on our PEI House of Commons.

For 20 May 1873 we have page 629, 634-635
For 21 May 1873 page 639, 644.

I think for 21 May it is simply: "Only entries relevant to confederation with Prince Edward Island selected."
(Or something like that, if we can generate a stock statement it would be useful).

As for 20 May 1873: if we could get a more authoratative statement on the use of page 629 (something about subsidies?) we can follow it up with the stock statement.

![pei_h_of_c_18730520_page_629](https://cloud.githubusercontent.com/assets/22153643/18961724/d40de8a4-8622-11e6-9238-418d022dd26e.jpg)

**Comment by DanielHeidt** [comment]
Hi Gord,

You are correct in principle, but a statement along the lines you suggest may not be adequate. The problem, simply put, is that we need to ensure that someone who is qualified to determine applicable and non-applicable content does the cutting. In the past, this has been me, but I would welcome the chance to give up this duty. Could we bring this up at the next meeting?

**Comment by martindholmes** [comment]
Look here:

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-samplingDecl.html

and link with #19.
