### ISSUE TITLE
Missing French OCR for PEI

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#24]
We have French transcriptions for PEI 1869-1870. From 1872 on, the right column is in english. THe right column has been added into the fr side of edited transcriptions. Therefore we have 15 english transcriptions that need to be merged back into the en side and we need to find French versions of said transcriptions.

Files in question are in data/PEI/Federal/hocr_edited/by_language/fr

PEI_H_of_C_1872_Page_01.hocr.html
PEI_H_of_C_1872_Page_02.hocr.html
PEI_H_of_C_1872_Page_03.hocr.html
PEI_H_of_C_1872_Page_04.hocr.html
PEI_H_of_C_1873_Page_01.hocr.html
PEI_H_of_C_1873_Page_02.hocr.html
PEI_H_of_C_1873_Page_03.hocr.html
PEI_H_of_C_1873_Page_04.hocr.html
PEI_H_of_C_1873_Page_05.hocr.html
PEI_H_of_C_1873_Page_06.hocr.html
PEI_H_of_C_1873_Page_07.hocr.html
PEI_H_of_C_1873_Page_08.hocr.html
PEI_H_of_C_1873_Page_09.hocr.html
PEI_H_of_C_1873_Page_10.hocr.html
PEI_H_of_C_1873_Page_11.hocr.html

**Comment by DanielHeidt** [comment]
We will not be publishing the French content from these pages because we cannot guarantee that a French-speaker reviewed this content. The project has focused on transcribing the Quebec-Ontario French debates.
