### ISSUE TITLE
Search/Replace for name mark-up

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#30]
Search/Replace tool is a huge timesaver for marking-up documents. Do we want to suggest volunteers use this?

The drawback is an error in the replace input can cause large amounts of errors in the document. Which is not difficult to fix but may discourage encoders. Plus there are at times variations in how a person is addressed (Sir or Hon. Sir, for example). There is the danger that an encoder does one, and misses a case or two of the other thinking that all the Macdonalds have been done.

Maybe offer both methods with a warning about the Search/Replace method?

Some of the debate days are lengthy and loaded with names, manually marking-up each name could be quite slow.

**Comment by martindholmes** [comment]
We should be able to teach people to use search-and-replace in a curated way: Find, then check by eye, then Replace (if correct) or Find again.
