### ISSUE TITLE
Middle name column used for other purposes in the personography spreadsheet

### ISSUE THREAD

**Issue by martindholmes** [TheCanadianConfederationDebates/TCCD#31]
In the personography spreadsheet, column E is supposed to be Middle Name, but it's also being used for a range of unrelated things ("Councillor", "brave", "Chief", "interpreter"). These mostly look like role names, so we should probably have a column for that purpose, and avoid mixing these very different data types together. Let me know if I should go ahead and make this change, or whether I'm missing something here.

**Comment by DanielHeidt** [comment]
Discard the email I just sent you on this. Yes, I have created the column as you suggested and moved the role data over.

**Comment by martindholmes** [comment]
Thanks Dan. Closing this.
