### ISSUE TITLE
Suggestion revisions to "Instructions.html"

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#35]
Please consider the following as possible revisions for "Instructions.html":

- The name of the file might be revised to something like "When you are finished.html"

- Once the files are ziped, should they be sent to Gord's email, or uploaded into the "Complete" folder on dropbox? Gord, please advise.

**Comment by lyallg** [comment]
Put in the TCCD Complete folder please.

**Comment by martindholmes** [comment]
@DanielHeidt Our original intention was to have that document link to Gord's instructions, which will be online somewhere, so that it becomes the simplest path to all the instructions; the "When you are finished" bit should be a heading inside the INSTRUCTIONS.html file. Would that make more sense? I wouldn't name a file with spaces in the file name.

**Comment by DanielHeidt** [comment]
> Our original intention was to have that document link to Gord's instructions

Sounds good to me. You are right, of course, that the file name should not have spaces - my point was that its name could be more descriptive if it is intended to communicate what a user should do when they finish processing a batch of files.

**Comment by DanielHeidt** [comment]
Upon reflection, should we simply move instructions you've developed on how to zip the finished xml files into Gord's manual and discard the "Instructions.html" file? If you have a different workflow in mind, that is ok too!

**Comment by martindholmes** [comment]
The point about the instructions file is that you can press the red triangle to run the zip task. Gord's instructions aren't in the package, so they can't have an action associated with them.

The manual could teach people how to download, install and use a zip client on their local machine, but I'd assumed that would be more complicated than just pressing the button.

**Comment by DanielHeidt** [comment]
Your point about the button makes good sense - but I did not understand how simple you were making it for the encoders from the paragraph in the Instructions.html file. This is ideal and should be kept, as you suggest. Could we perhaps revise the wording to make that purpose / utility clearer?

**Comment by martindholmes** [comment]
Gord, can you edit `code/encoder_package/project/INSTRUCTIONS.html` to make it say what it needs to say about how to return the zip file to the project?

**Comment by lyallg** [comment]
Will do.
