### ISSUE TITLE
Pages when no historical figure is identified on the page

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#36]
This is a note for pages when no speaker is identified (ex. lgHC_PEI_1870-03-21). These typically occur in debates on the address, when we only care about a passing comment made by an individual about Confederation. In these cases, one of us will have to: 1) delete the superfluous text, 2) add the historical figure's name to the text, 3) encode the name.

This workflow description is not yet complete. In our last meeting, Martin stated that he will need to determine how to encode these snippets. Where this additional encoding will fit into the workflow will also have to be described.

**Comment by martindholmes** [comment]
I think the most straightforward thing to do is to use the `<add>` tag for the added name. An example of this might be put into the guide.

**Comment by martindholmes** [comment]
Assigning to Gord to add an example to the guide based on this encoding:

~~~~~
<p><add><persName ref="pers:LACE1">Hon Mr. Lacemaker</persName></add>....</p>
~~~~~

**Comment by lyallg** [comment]
Will do.

**Comment by martindholmes** [comment]
@lyallg is this done now?

**Comment by martindholmes** [comment]
@lyallg can we close this ticket?

**Comment by martindholmes** [comment]
I've added output handling for this. @lyallg can we close it?

**Comment by lyallg** [comment]
Yes. We can close this.
