### ISSUE TITLE
A different file organization for PEI Federal

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#38]
This was the first set of debates worked on. My mo has been to leave file structure as is and work within, so right now all images and xml are linked up but this group has a slightly different organization as the rest. Instead of "English" and "French" as children of "Federal" we have all our files and folders in "Federal" and then within final/hocr we have an "en" folder which was designed to reflect how hocr_edited folder is set-up: by_langauge/en.

As stated right now all links work, if we want to change the organization to match other folders it will require changing the file paths in all targets.

Is this worth while or are we ok with this aberrant structure?

**Comment by DanielHeidt** [comment]
Good catch, and I agree that it is ok to leave this as is.

**Comment by martindholmes** [comment]
I think my code (that builds the encoder package) actually parses the relative links in the facsimile/surface/graphic elements to find the images, so (assuming you've tried it and it successfully builds the package, including the images) there should be no need for a change.

**Comment by lyallg** [comment]
Yep, build went ok, images are all there.

**Comment by martindholmes** [comment]
Closing, since I believe this is no longer an issue.
