### ISSUE TITLE
Volume data needs to be imported from spreadsheet into Personography

### ISSUE THREAD

**Issue by martindholmes** [TheCanadianConfederationDebates/TCCD#42]
I've already made a start on this. It turns out we should have brought into the personography.xml file a flag for every time something occurred in one of the volume columns for a given person. In practice, this means adding `@source="bibl:XXXXD"` to each `<affiliation>` element in the personography. These are the steps:

1. DH creates a bibliography of all the volumes.
2. One of the HCMC folks marks up the bibliography in TEI, assigning ids to each entry.
3. MH writes code to create the `@source` attributes.

In commit https://github.com/TheCanadianConfederationDebates/TCCD/commit/038af733bc60a3e70f00f41a63b271356cc67dfd I added a basic XSLT transformation which grabs the relevant data from the expanded FODS version of the personography and generates a list of items like this:

`<ref target="pers:ARCH1" n="3">bcHofCCol</ref>`

meaning "the third affiliation element in ARCH1's personography entry needs to be decorated with @source pointing to the BC H of C volume." This is stored in data/personography/affils_to_volumes.xml. When the bibliography is ready, these pointers need to be turned into the correct ids, and then this data needs to be merged into the personography with an identity transform.

**Comment by DanielHeidt** [comment]
Draft bibliography has been emailed to @martindholmes and @lyallg .

**Comment by martindholmes** [comment]
Closing this ticket since I've imported the relevant data into the personography.xml file. Will open a new one for encoding the bibliography.
