### ISSUE TITLE
Appendixes

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#59]
APPENDIXES (Terms of Union- BC Prov; and Bill of Rights Convention 40)
--- Where to put them, or can we find dates and make Debate Day?

**Comment by DanielHeidt** [comment]
These belong to the volumes that they are currently attached to. Can we attach them as "documents"?

**Comment by lyallg** [comment]
For BC we can add them to the end of the last debate day.
For Convention Forty, Appendix A can also be added at the end of last debate day, but Appendix B has its own date, I think it should get its own page? Or maybe not?

**Comment by DanielHeidt** [comment]
Yes, this all sounds good. Please proceed as you describe above.
