### ISSUE TITLE
Morris book: chapters with no people tagged

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#64]
In Morris_Chapter_12 we have an image that should be inserted (in lieu of providing page images).

This code works in schema:
`<figure>`
`<figDesc>description...</figDesc>`
`<graphic` url=""/>
`</figure>`

Need to  devise a protocol for storing images and linking to them.

**Comment by lyallg** [comment]
DH recommends deleting last page from this chapter. GL will do in June unless new decision made in MAy,

**Comment by martindholmes** [comment]
@lyallg to identify all images that need to be included.
@martindholmes to figure out how to store and link to images, then add processing to the build to insert them in the output HTML.

**Comment by martindholmes** [comment]
@martindholmes to fix the build so that Morris chapters without tagged people are still processed.

**Comment by martindholmes** [comment]
Morris book has been shown on the site for a while, so this is no longer relevant.
