### ISSUE TITLE
Adding additional display info in personography

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#73]
Display placeography <notes> when adding placeography IDs to Indigenous <placename> in personography.

**Comment by martindholmes** [comment]
@DanielHeidt could you check whether this is working for you now? I think I did it, but I'm not 100% clear I remember exactly what was being requested.

**Comment by DanielHeidt** [comment]
@martindholmes I think this still needs to be implemented. I think the problem is that, for Indigenous personography entries, "ref" isn't correctly linking to the placeography within the <placeName> tags... assuming I'm using the right syntax.

**Comment by martindholmes** [comment]
So this is a modification to the schema that's required, right?

**Comment by DanielHeidt** [comment]
<placeName ref=""> still appears to be displaying personography IDs instead of placeography IDs.

**Comment by martindholmes** [comment]
OK, this is next on my list.

**Comment by martindholmes** [comment]
Done in commit #5ee3538e3.
