### ISSUE TITLE
EN and FR button functionality

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#78]
For many pages there will be no French text for a debate day, but in the case of Manitoba, there is.

I went to http://hcmc.uvic.ca/tccd/fr/lgAssinLAssem_1870-03-15.html and it appears that “EN” and “FR” buttons are not quite working right. When I try to switch to the French page, the browser to http://hcmc.uvic.ca/tccd/fr/lgAssinLAssem_1870-03-15.html (which currently displays English text) instead of http://hcmc.uvic.ca/tccd/en/lgAssinLAssem_fr_1870-03-15.html (which correctly displays the French text). 

It appears that there is just a minor bug in where the "fr" appears in the URL.

**Comment by martindholmes** [comment]
Switching between French and English is currently for the interface, not for the documents. You can read an English document with a French interface and a French document with an English interface. Equivalence between documents which purport to be translations of each other would need to be established in a formal way, and those links supplied in a different form. I don't want to jump to a French version of a document to check something and have the whole interface change as well, when I'm used to working in the English interface.

**Comment by DanielHeidt** [comment]
Thank you for pointing out the current structure and emphasizing that this would require some additional steps. If we choose to proceed, the only debates that have French-English versions are the "provincial" debates for Ontario-Quebec and Manitoba. Since both languages have the same debate days, it would not be hard to generate a list one each volume is fully converted into XML and the site rebuilt. Could we, perhaps, load both sets of debate days one the same page, and then hide the non-applicable language, as we do for the header, landing page etc... using <lang>? This would eliminate any need for additional code for the language preference buttons, but may (to what extent I am not sure) complicate the website rebuild process. What do you think?

**Comment by martindholmes** [comment]
My plan for the two-language process is to split out the pages anyway, so I don't think we need to combine them. If the ids of pages with a corresponding page in the other language are (as they should be) predictable, so you can derive one from the other, we can just check if there's a French or English version of each debate day and provide a special link to it. But there should be a French and an English version of each page in each language, surely?

**Comment by DanielHeidt** [comment]
These options sound good to me. Shall we leave this ticket open for now as a record of what we think the functionality will eventually be?

**Comment by martindholmes** [comment]
Yes, let's do that.

**Comment by martindholmes** [comment]
I believe this is now complete.
