### ISSUE TITLE
Deploying House of Commons Taxonomy to Improve Browsing

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#79]
I was wondering whether we could use taxonomy to re-aggregate the House of Commons debates so that they can be browsed like the provincial debates?

For example, the Manitoba Convention of 40 debates can be browsed together at http://hcmc.uvic.ca/tccd/lgConv40.html. The House of Commons debates on Manitoba, however, can only be accessed by browsing all H of C debates at http://hcmc.uvic.ca/tccd/lgHC.html. In this case, could a "House of Commons" page be added to the list at http://hcmc.uvic.ca/tccd/contents.html by using the "lgHC_MB" ID listed in the taxonomy? If this is possible, I assume the same could be done for the House of Commons debates concerning other provinces as well?

This functionality will be key for Frank as he develops the interface for those who want to research a particular province's records via. debate day, rather than by riding.

**Comment by martindholmes** [comment]
I guess so.

**Comment by martindholmes** [comment]
Done in commit cf50120f5.
