### ISSUE TITLE
A few xml issues for build/CSS

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#82]
Using lgNSLA_1865-04-21 as example:

1.
In this document this is how '<choice>' element is being rendered on website: railwvyrailway
- the code = `<choice><sic>railwvy</sic><corr>railway</corr></choice>`

I assume we want "railway" to replace the typo, maybe highlighted with hover explanation?

2.
`<p rendition="simple:right">FRIDAY, April 21.<lb/>` 
Appears on the left of the page instead of the right

rendition="simple:centre"  works (and "simple:right" works within tables)

3.
Martin: Does your build handle `<emph>` tags? We have some of those too. 

AND

`<unclear reason="illegible">`[?]`</unclear>`

**Comment by DanielHeidt** [comment]
Please create display that will show intended text and then a hover-over for user to see original text.

**Comment by martindholmes** [comment]
Bug 2 should be fixed today.

**Comment by martindholmes** [comment]
Re point 3:

~~~~~
<div type="section">

<head rendition="simple:centre">Provincial Parliament</head>
            
<p rendition="simple:centre"><emph>House of Assembly</emph></p>
           
 <p rendition="simple:right">THURSDAY, April 27th.</p>
            
            <p> This day...</p>
</div>
~~~~~

**Comment by martindholmes** [comment]
These look like heads to me, so I'll fix the schema to allow multiple head elements.

**Comment by martindholmes** [comment]
Completed the rest of this by commit #32e4d5cec.
