### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#85]
Change around some of the content in the popups (I don't believe any new content has to be generated) to match the attached example.

The example was designed from the map popup, but I think it is readily adaptable to the popups that appear in the debate days.

Once the content displays in the correct order, Frank said he'll take care of any remaining aesthetic issues.

[website design popup template.docx](https://github.com/TheCanadianConfederationDebates/TCCD/files/1488202/website.design.popup.template.docx)

**Comment by martindholmes** [comment]
Done.

**Comment by DanielHeidt** [comment]
@martindholmes changes look great. @FrankFlitton please finish styling according to my suggestions.

**Comment by DanielHeidt** [comment]
A minor bug report. On a French debate day, the popups display the links to other English documents from the same historical figure. See, for example, this screenshot from David Ressor on http://hcmc.uvic.ca/confederation/fr/lgPCLC_fr_1865-02-13.html. 

<img width="321" alt="screen shot 2018-01-03 at 11 42 13 am" src="https://user-images.githubusercontent.com/16122501/34529843-3d733448-f07b-11e7-8376-b20a01aa0442.png">

Fixing this is probably just a matter of adding some additional language sensitivity to the build process that populates these popups?

**Comment by martindholmes** [comment]
Does look like a bug. However, there's a decision to be made too: if there's no French equivalent to an English-language document, should the English document be included in lieu?

**Comment by DanielHeidt** [comment]
Thanks for the quick response. If we listed English language texts when the French are unavailable, would it be possible for these entries to have "(en anglais seulement)" listed after — or as part of —the link?

**Comment by martindholmes** [comment]
Fixed as part of work on another ticket today.
