### ISSUE TITLE
Insert bibliography info at bottom of debate days

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#86]
The bottom of each debate day should list the organization that provided us with the records. This information is available in bibliography.xml. 

For example, on http://hcmc.uvic.ca/tccd/en/lgNSLA_1865-02-09.html, please insert the following text between "The Address was allowed to lie on the table. The House adjourned until three o'clock the next day." and "Participating individuals."

"Early Canadiana Online [word should be linked to URL in <ref target>] generously provided its copy of these debates to _The Confederation Debates_ at no cost to the project.

**Comment by DanielHeidt** [comment]
I can build some of this into the bibliography or taxonomy if that would be helpful.

**Comment by martindholmes** [comment]
The info would have to be available in processable form before we can process it. How do we know which organization provided which data?

**Comment by DanielHeidt** [comment]
I have that information. I will just need a bit of instruction on where to put it. For example, I believe I have already inputed most / all of what we need for NS in bibliography.xml. Do you need me to input the company name "Early Canadiana"? If yes, what tag should it be entered into?

**Comment by martindholmes** [comment]
I need to know how it's going to be used before we can figure out what goes where. Discuss this tomorrow?

**Comment by DanielHeidt** [comment]
Sounds good. We can iron out the details tomorrow and make some notes here if necessary after.
