### ISSUE TITLE
Yukon files

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#87]
I tried uploading them to the website for the volunteers to work on and only some of the files are loading correctly. I’m getting the following error when I try to load the problematic files:
Not Found

HTTP 404 (GET /page/)

[/home/watinnov/transcribe-app/vendor/bcosca/fatfree/lib/base.php:1532] Base->error()
[index.php:217] Base->run()

Not sure what the problem is. I’ve attached two sample files—page 1 fails, page 3 loads correctly. Any idea what the problem with page 1 might be?
[examples.zip](https://github.com/TheCanadianConfederationDebates/TCCD/files/1488923/examples.zip)

**Comment by martindholmes** [comment]
Not a problem with the files; they're both valid. Have to take this up with the people who wrote the software, I'm afraid.

**Comment by DanielHeidt** [comment]
Sadly the programmers have all moved on to other position and can only provide minimal support. 

I'd like to propose the following alternative solution. Could you please provide me with an html file with the basic header info etc... that would allow me to have Ruby type each of these documents out in Oxygen?

**Comment by martindholmes** [comment]
I'm swamped with other work right now; I've been trying to put time into the treaties. Do you want to make this the priority instead?

**Comment by martindholmes** [comment]
Incidentally, anyone can create a new XML file based on an existing one and copy/paste the text of the transcription into it from the HOCR page. You don't need me for that.
