### ISSUE TITLE
Page number display issue on legacy website

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#88]
In some debate days the page numbers and other header information are being displayed together. Take, for example, http://hcmc.uvic.ca/confederation/en/lgHC_AB_SK_1905-03-15.html displays the text "2497 MARCH 15, 1905 2498". Instead, only the page numbers should be listed. I spoke with @lyallg and he thought that fixing this was just a matter of discarding the separately encoded date content.

Is this correct?

**Comment by lyallg** [comment]
I don't recommend discarding the info, but `<fw>` can be suppressed if we don't want it shown on website. Or maybe ignore them in the build?

**Comment by DanielHeidt** [comment]
Sorry, poor choice of words. Yes, I meant that it could be ignored during the build.

**Comment by martindholmes** [comment]
You can discard it or hide it. I've hidden it in the CSS, so it shouldn't show up in the next build.

**Comment by martindholmes** [comment]
Do you also want to hide running headers as in "COMMONS" on this page?

http://hcmc.uvic.ca/confederation/en/lgHC_AB_SK_1905-03-01.html

**Comment by DanielHeidt** [comment]
Yes please. That would be great.

**Comment by martindholmes** [comment]
Fixed in #ce5b326f6.
