### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#89]
When all encoding is complete, we'll need to build a search function into the website. I add the ticket here merely as a reminder.

**Comment by DanielHeidt** [comment]
Fine by me.

**Comment by martindholmes** [comment]
Google search is done and working as of commit 8dbf989d7. All pages except for the ones custom-created have a search button in the top right; when Frank gets a chance, he can add a search button to the menus of pages in code/html.

**Comment by martindholmes** [comment]
Is Frank ever doing anything else, or should we just do this ourselves?

**Comment by martindholmes** [comment]
Decision: do this ourselves for now to make the button available, then FF can tweak if he wishes later.

**Comment by DanielHeidt** [comment]
Search icon and link to gSearch.html now added to all custom pages.
