### ISSUE TITLE
Postal code map functionality

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#91]
After zooming in and out of the map, popups appear to be displaying outside of frame and cannot be accessed by users.

Also, please have all links clicked from map popup appear in a new tab. Rationale: if the user clicks "back" the map resets and they lose their spot. By opening a debate day selected from this map interface in a new tab, the user can always go back and select another nearby riding.

**Comment by martindholmes** [comment]
Could you make this into a proper bug report:

 - Operating sytem
 - Browser
 - Exact sequence of actions
 - Result
 - Screenshots

The new-tab thing should be a separate ticket; are there other contexts where you also want to pre-empt the user's control over tabs/windows in the browser, or just in the map?

**Comment by DanielHeidt** [comment]
Sure.
The issue appears to related to scrolling on the page after the popup has been called.

Here is the info you requested:

- OSX 10.12.6
- Chrome 62.0.3202.94
- sequence

1. go to http://hcmc.uvic.ca/confederation/en/index.html
2. Zoom in on a random riding and click it
3. The popup appears half outside of the page (see first screenshot)
<img width="1164" alt="1" src="https://user-images.githubusercontent.com/16122501/33051457-f2dd39a2-ce37-11e7-8e56-fed1d828c4be.png">
4. Scroll down the page to view other parts of the website without clicking any links
5. then scroll back up to the map and view the popup—which now appears further up the page (see second screenshot).
<img width="1090" alt="2" src="https://user-images.githubusercontent.com/16122501/33051485-1203d016-ce38-11e7-8af6-f2099cad45fe.png">

**Comment by martindholmes** [comment]
Nothing appears outside the page; the popups appear above the map, and always in the same place. (If they're bigger, they take up more screen space, of course.) Where exactly would you like them to appear?

**Comment by DanielHeidt** [comment]
@FrankFlitton - modify header so that it stays same height. Currently on mobile size the header goes into a single column. Instead, please have the header switch to a three bar button that can be clicked to expand the menu.

**Comment by martindholmes** [comment]
I've just tested this on two versions of OSX and I can't reproduce it. Either Chrome fixed a bug, or an update to OpenLayers solved it.
