### ISSUE TITLE
Bibliography French vs. English texts

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#92]
In most cases this won't matter but, for volumes like Ont-Que (id=lgOQ), bibliography.xml likely needs to differentiate between English and French texts. The reason is that our digitization source companies are different. 

Should this metadata be accommodated within a separate <bibl> entry, or is there a way to use <lang> within an existing entry?

**Comment by martindholmes** [comment]
Are these bibliography items for the original source documents or for a digitized version provided by a company?

**Comment by DanielHeidt** [comment]
It would be the digitising work, which we need to display on the website.
Is this better done in the taxonomy or the bibliography?


Dan

**Comment by martindholmes** [comment]
If there's always a one-to-one correspondence between a specific bibliography entry and the agent who digitized it, then we can add this as a property of the bibliography entry. If it gets more complicated than that, then we'll have to think again.

**Comment by DanielHeidt** [comment]
Yes it is a one to one ratio, so I assume I should continue to enter these
links I to the bibliography like I did for NS and parliament?

**Comment by martindholmes** [comment]
Right now the bibliography has some entries with `<ref target="http://parl.canadiana.ca/">http://parl.canadiana.ca/</ref>` in them; that just means that the content is available there. If you want to say something specific about some role or action that a person or an organization took with regard to the processing or provision of that content, then we need to do something more solid and detailed, probably in the form of responsibility statements. Who did what, exactly?

**Comment by DanielHeidt** [comment]
We could go the route you suggest. The end goal is a simple statement of who digitized the records that can appear on each debate day (this is what I promised the owners of the digitized copies). In a few cases, where no digitized copy previously existed, we would be listing the URL of the archive that holds the records (ex. the PEI archives' landing page). We could, I suppose also state that The Confederation Debates did the digitizing, though I don't particularly care about the project getting the credit for this.

Alternatively, does the existing `<ref target="http://parl.canadiana.ca/">http://parl.canadiana.ca/</ref>` structure sufficient communicate availability in a general way?

I leave it to your discretion and am glad to do the data entry for whichever fits better with best practices.

**Comment by martindholmes** [comment]
"Who digitized the records" is different from who owns the digitized copies or what the original source document is. We need to disentangle these things. A URL is not a statement of ownership or of responsibility; it just says "go here to find this stuff". If we're giving credit and assigning responsibility, we need to use responsibility statements which point to a taxonomy of responsibilities and a list of orgs and/or people.

**Comment by DanielHeidt** [comment]
Let's chat about this again during the meeting today. I think you and I are using this data for different purposes—which is totally fine. I think the goal today will be for each of us to first clearly express what we want the metadata to do (rather than what is possible) and then determine the best data structures for entering it once and for all so that it fully meets both of our needs.

**Comment by martindholmes** [comment]
We need to identify:

1. Orgs/people who created digital images of either their own content or someone else's, and they are serving those images. We took and used those images.
2. Records not digitized by the original host that were digitized by us. E.g. the PEI archives provided access to their documents, but we created the digital images.
3. Out-of-copyright materials found in digitized form on archive.org which we just took and used.
4. Materials already transcribed and encoded in (for instance) HTML, which we simply take and transform into TEI.

The idea would be: 

1. Create an orgography for the orgs involved.
2. Add respStmts to bibliography entries which link to the orgs and possibly also to online locations of sources.
3. Process the respStmt info into each individual page which results from that biblio source.

**Comment by DanielHeidt** [comment]
Update: this element appears to now be working correctly for the English-language treaties. French languages pages of the same treaties are not working. Ex. http://hcmc.uvic.ca/confederation/fr/treaty_fr_09.html. Is there some data entry that I need to do or is this a linking problem?

**Comment by martindholmes** [comment]
When I go here:

http://hcmc.uvic.ca/confederation/fr/treaty_fr_09.html

and click on EN, I correctly go here:

http://hcmc.uvic.ca/confederation/en/treaty_09.html

If you think this is wrong, could you please explain why?

**Comment by DanielHeidt** [comment]
The problem is not the link per se. It is the "Source" section near the end of the document which reads " [Error: no source found for treaty_fr_09 (09).] The header for this bibliographic entry is also English.

**Comment by DanielHeidt** [comment]
Resolved by commit #c9240f428.
