### ISSUE TITLE
Process Numbered Treaties

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#96]
Please process all of the following Numbered Treaties into TEI.

https://www.aadnc-aandc.gc.ca/eng/1100100028664/1100100028665
https://www.aadnc-aandc.gc.ca/fra/1100100028664/1100100028665
https://www.aadnc-aandc.gc.ca/eng/1100100028675/1100100028679
https://www.aadnc-aandc.gc.ca/fra/1100100028675/1100100028679
https://www.aadnc-aandc.gc.ca/eng/1100100028689/1100100028690
https://www.aadnc-aandc.gc.ca/fra/1100100028689/1100100028690
http://www.aadnc-aandc.gc.ca/eng/1100100028699/1100100028700
http://www.aadnc-aandc.gc.ca/fra/1100100028699/1100100028700
https://www.aadnc-aandc.gc.ca/eng/1100100028710/1100100028783
https://www.aadnc-aandc.gc.ca/fra/1100100028710/1100100028783
http://www.aadnc-aandc.gc.ca/eng/1100100028793/1100100028803
http://www.aadnc-aandc.gc.ca/fra/1100100028793/1100100028803
http://www.aadnc-aandc.gc.ca/eng/1100100028813/1100100028853
http://www.aadnc-aandc.gc.ca/fra/1100100028813/1100100028853
http://www.aadnc-aandc.gc.ca/eng/1100100028863/1100100028864
http://www.aadnc-aandc.gc.ca/fra/1100100028863/1100100028864
https://www.aadnc-aandc.gc.ca/eng/1100100028874/1100100028906
https://www.aadnc-aandc.gc.ca/fra/1100100028874/1100100028906
https://www.aadnc-aandc.gc.ca/eng/1100100028916/1100100028947
https://www.aadnc-aandc.gc.ca/fra/1100100028916/1100100028947

**Comment by martindholmes** [comment]
My bit is done, and the half-assed XML is with Gord for proper nurturing.
