### ISSUE TITLE
Postal code on mobile - not clickable

### ISSUE THREAD

**Issue by DanielHeidt** [TheCanadianConfederationDebates/TCCD#97]
When I access the map on mobile, I am unable to see the popups on postal code map. I did some further testing with my computer and discovered the following:
- If I browse the map and click a node on my computer with the screen on normal width, everything works. If I then resize the browser window to phone screen size, the popup still appears in the right place and updates correctly.
- If, on the other hand, I do a hard refresh of the landing page, narrow my window to phone screen width, and then try to select a node, no popup appears. Even if I then widen the page, no popup appears.

Since the same problem appears to be occurring for Android and OSX Chrome (both are up to date), I assume that the problem has something to do with the way the map popup is first generated and updated.

If you cannot reproduce the problem, I can show you next week.

**Comment by martindholmes** [comment]
Do you still see the problem here?

http://hcmc.uvic.ca/confederation/en/canadaMap.html

If not, then it's basically a style issue. The decision to host the map in the middle of a bunch of other content was a mistake in my view, but if you're committed to it, then it's the designer's job to figure out where things should appear on different platforms.

**Comment by DanielHeidt** [comment]
@FrankFlitton, could you please look into this when you have a chance.

**Comment by martindholmes** [comment]
Is this problem still there?

**Comment by martindholmes** [comment]
This is a problem only with Chrome, but it seems like touch is not firing click as expected; the icons for locations are probably too small, which may be the problem but possibly not. Make them bigger for mobile.

**Comment by martindholmes** [comment]
I think this is now working. To confirm the fix, you'll need to clear the cache in your mobile browser and reload the map page.

**Comment by DanielHeidt** [comment]
Works for me on Android Mobile Firefox, but I'm still having trouble on Chrome. On Chrome I am able to bring up the info from one node, but the popup is usually for a different node than the one I clicked. I am unable to select a different node without refreshing the page.

**Comment by martindholmes** [comment]
I saw that too, but I wasn't sure whether it was a cache issue. If you're seeing it too, then this is still a problem. We'll also have to test with iOS Safari. I can't see why this map would be different from any of the others we've built with OpenLayers, although the postcode bar at the bottom is using flex CSS, so perhaps that has something to do with it.

**Comment by martindholmes** [comment]
I no longer see this problem. Closing the ticket.
