### ISSUE TITLE
XSLT for `<head>'

### ISSUE THREAD

**Issue by lyallg** [TheCanadianConfederationDebates/TCCD#99]
Martin, please transform `<p rendition="simple:centre">` that is NOT within `<quote>` to `<head>` and remove any `<emph>` ; also `<p rendition="simple:right">` NOT in quotes that either follow a `<head>` or begin after a `<div>`

Thanks.

- Gord

**Comment by martindholmes** [comment]
There are huge numbers of `<p>` elements matching this description which can't be converted to `<head>` elements because they have preceding-siblings which are not `<head>`s. Those will have to be ignored...

**Comment by martindholmes** [comment]
XSLT created and in the repo; ran it on the existing document set and committed the changes. If more docs with this problem appear, we can run it on them. It often has to be run two or three times because of multiple instances in the same place.
